### ISSUE TITLE
sub-assign to integer64 does not handle function form

### ISSUE THREAD

**Issue by jangorecki** [truecluster/bit64#1]
Hi Jens,
Thanks for bit64 package.
It seems that `[<-` is now well handled. Would be nice to have to working as it is sometimes useful.
I am on 0.9.7.
```r
library(bit64)
x <- as.integer64(1:3)
v <- as.integer64(4)
x[1L] <- v
x
#integer64
#[1] 4 2 3
`[<-`(x, 1L, v)
#Error in as.integer64(value) : 
#  argument "value" is missing, with no default
```
It could work just like an integer
```r
x <- 1:3
v <- 4L
x[1L] <- v
x
#[1] 4 2 3
`[<-`(x, 1L, v)
#[1] 4 2 3
```

**Comment by joehl** [comment]
Hi Jan,
bit64 on github starts with Version: 4.0.0 and the reported (past) issue is not an issue in this version.

**Comment by jangorecki** [comment]
This is very good news. Thanks. Feel free to close this issue then. I looked at NEWS file and haven't seen that mention, you could consider to mention it there.
