### ISSUE TITLE
Bitwise operations missing

### ISSUE THREAD

**Issue by OfekShilon** [truecluster/bit64#16]
Old bit64 versions had `bitOr` and `bitAnd`. The github versions don't have them, but NEWS doesn't have any mention of dropping them deliberately in any prior version. Could they have been accidentally deleted?

**Comment by MichaelChirico** [comment]
The CRAN history also shows no such function, maybe it was a different package?

https://github.com/cran/bit64

**Comment by truecluster** [comment]
Perhaps CRAN package ```bitops```? 
I can't remember those in bit64.
