### ISSUE TITLE
bit64 NA doesn't replicate in data.frame constructor

### ISSUE THREAD

**Issue by shubham1637** [truecluster/bit64#2]
While constructing a data-frame, columns are replicated if lengths differ.
```
> data.frame(x = c(1,2), y = NA_integer_)
  x  y
1 1 NA
2 2 NA
```
However, when I try to do this with `bit64::NA_integer64_`, I get an error. Does anyone know what could be happening? `rep()` works if it is called separately on `bit64::NA_integer64_`.
```
> data.frame(x = c(1,2), y = bit64::NA_integer64_)
Error in data.frame(x = c(1, 2), y = bit64::NA_integer64_) : 
  arguments imply differing number of rows: 2, 1
> rep(bit64::NA_integer64_, 2)
integer64
[1] <NA> <NA>
```

**Comment by truecluster** [comment]
'integer64' is not a native data type and R Core does not support non-native data types in their functions such as 'data.frame'. There is nothing a package author can do (other than switching to a decent language such as Julia).
