### ISSUE TITLE
Round trip with `dput()` and `hexNumeric`?

### ISSUE THREAD

**Issue by jonkeane** [truecluster/bit64#27]
I see in the examples for bit64 that roundtripping with `dput()` is supported. But I noticed that if I use the deparse option `hexNumeric` (to get the best fidelity for floats in roundtrips, https://stat.ethz.ch/R-manual/R-devel/library/base/html/deparseOpts.html), I'm getting `0` as the return value for many bit64 integers:

``` r
library(bit64)

d_file <- tempfile()

int32 <- 10
int64 <- as.integer64(10)

# for a standard integer, we can roundtrip with dput
dput(int32, d_file, control = c("all", "hexNumeric"))
back <- source(d_file)$value

identical(int32, back)
#> [1] TRUE

# for bit64, hexNumeric doesn't roundtrip
dput(int64, d_file, control = c("all", "hexNumeric"))

back <- source(d_file)$value

identical(int64, back)
#> [1] FALSE

int64
#> integer64
#> [1] 10
back
#> integer64
#> [1] 0

# though digits17 does work
dput(int64, d_file, control = c("all", "digits17"))

back <- source(d_file)$value

identical(int64, back)
#> [1] TRUE
```

<sup>Created on 2022-12-30 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

This might ultimately be a limitation or issue with R's representation of binary fractions with floats that are lower than `.Machine$double.xmin` (which apparently _can_ occur https://stat.ethz.ch/R-manual/R-devel/library/base/html/zMachine.html), since a large enough integer64 does roundtrip (see below).

``` r
library(bit64)

d_file <- tempfile()

# but a large integer64 does roundtrip
int64_large <- as.integer64(.Machine$integer.max) * .Machine$integer.max

dput(int64_large, d_file, control = c("all", "hexNumeric"))

back <- source(d_file)$value

identical(int64_large, back)
#> [1] TRUE
```

<sup>Created on 2022-12-30 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by truecluster** [comment]
Jonathan,

I have no clue why dput strips of structure with control="hexNumeric".

Why don't you use serialize/unserialize?

Kind regards

Jens

**Comment by truecluster** [comment]
Not our fault
