### ISSUE TITLE
Implicit coercion to double/numeric 

### ISSUE THREAD

**Issue by alkment** [truecluster/bit64#6]
When one tries to implicitly coerce an integer64 to a numeric one gets a tiny numeric.

Also it's odd that if the order is changed the results change. I assume this is because of the single dispatch.
Since numeric is the base R type a numeric should probably and the coercion should be the same as explicit coercion i.e. as.numeric().
```
> c(1,as.integer64(1))
[1]  1.000000e+00 4.940656e-324
> c(as.integer64(1),1)
integer64
[1] 1 1

> as.vector(as.integer64(1))
[1] 4.940656e-324
```

Probably related to [this](https://github.com/truecluster/bit64/issues/5)

Session Info:
R version 4.0.2 (2020-06-22)
Platform: x86_64-redhat-linux-gnu (64-bit)
Running under: Fedora 32 (Workstation Edition)

Matrix products: default
BLAS/LAPACK: /usr/lib64/libopenblas-r0.3.9.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C
 [9] LC_ADDRESS=C               LC_TELEPHONE=C
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base

other attached packages:
[1] bit64_4.0.5 bit_4.0.4

loaded via a namespace (and not attached):
[1] compiler_4.0.2    data.table_1.13.2

**Comment by truecluster** [comment]
So what? Was this a question? A suggestion? R has no native 64bit integers! If you try to fix this with a package, you stumble over somewhat broken S3 dispatch or you have to use slow S4-dispatch, additionally CRAN maintainers don't allow you to do things such as defining as.vector.integer64(). Package maintainers have no control over what R does in c() or data.frame(). If you want proper types and proper dispatch, why not use a proper language such as Julia?

**Comment by alkment** [comment]
My post raises an issue and suggests a solution.

The issue is that if call as.vector() or c() on the 64bit int it becomes useless.  I suggest that c should convert to numeric the same way as.numeric() does if there are data types other than 64bit integer in the function call. For as.vector it should  remain a valid 64bit int. 

The bit64 package is awesome in that it allows us to work with data sets we might otherwise not be able to work with.
I understand that there might be certain issues (CRAN , c being a R internal ...) with implementing the suggestions. Maybe the R foundation can be lobbied into implementing appropriate c() and data.frame() methods for 64bit ints.

**Comment by truecluster** [comment]
Try lobbying the R foundation. As a package author I can't do anything about this. Because of single dispatch I have no control over the code running when c(otherclass, myclass).  And if my code c.integer64 is running, I coerce everything else to integer64 for good reasons.
