### ISSUE TITLE
mean.integer64 method could return numeric

### ISSUE THREAD

**Issue by jangorecki** [truecluster/bit64#7]
Hello,
Base R `mean` on integers will always return numeric. Would you consider aligning this behavior in bit64?

**Comment by truecluster** [comment]
Jan,
integer64() are deliberately different from integer and from double:

`
> require(bit64)
> 
> # consider a value that double cannot count anymore
> x <- lim.integer64()[2]
> 
> # this mean is exact
> mean(c(x, x-2))
integer64
[1] 9223372036854775806
> 
> # well, as exact as it can be
> mean(c(x, x-1))
integer64
[1] 9223372036854775806
> 
> # similar with quantiles
> quantile(x-(0:100))
integer64
                 0%                 25%                 50%                 75%                100% 
9223372036854775707 9223372036854775732 9223372036854775757 9223372036854775782 9223372036854775807 
> 
> # note that these are meaningful distinguishable quantiles
> unique(quantile(x-(0:100)))
integer64
[1] 9223372036854775707 9223372036854775732 9223372036854775757 9223372036854775782 9223372036854775807
> 
> # if you want numeric results you always can 
> mean(as.double(c(x,x-2)))
[1] 9.223372e+18
Warnmeldung:
In as.double.integer64(c(x, x - 2)) :
  integer precision lost while converting to double
> # or
> as.double(mean(c(x,x-2)))
[1] 9.223372e+18
Warnmeldung:
In as.double.integer64(mean(c(x, x - 2))) :
  integer precision lost while converting to double
> 
> # but note that you cannot undo the precision loss
> as.integer64(mean(as.double(c(x,x-2))))
integer64
[1] <NA>
Warnmeldung:
In as.double.integer64(c(x, x - 2)) :
  integer precision lost while converting to double
> # actually the implementation returns NAa above ~ 2^52
> 
> # similar with quantiles
> quantile(as.double(x-(0:100)))
          0%          25%          50%          75%         100% 
9.223372e+18 9.223372e+18 9.223372e+18 9.223372e+18 9.223372e+18 
Warnmeldung:
In as.double.integer64(x - (0:100)) :
  integer precision lost while converting to double
> as.double(quantile(x-(0:100)))
[1] 9.223372e+18 9.223372e+18 9.223372e+18 9.223372e+18 9.223372e+18
Warnmeldung:
In as.double.integer64(quantile(x - (0:100))) :
  integer precision lost while converting to double
> 
> # note that using double all the quantiles are the same (not meaningful)
> unique(quantile(as.double(x-(0:100))))
[1] 9.223372e+18
Warnmeldung:
In as.double.integer64(x - (0:100)) :
  integer precision lost while converting to double
`

**Comment by jangorecki** [comment]
Thanks for prompt reply. I now realized that
```r
mean(as.integer64(c(3,4)))
```
is not returning 3.5 but a whole number. Therefore there is no reason to return numeric type when it always returns whole numbers.
