### ISSUE TITLE
Not able to handle big integer 

### ISSUE THREAD

**Issue by sclewis23** [truecluster/bit64#9]
I'm getting some strange results when I try using very large integers from MS SQL Server.

`
``` r
# max -9223372036854775808 = NA
bit64::as.integer64(-9223372036854775808)
#> integer64
#> [1] <NA>
# max 9223372036854775807 = NA
bit64::as.integer64(9223372036854775807)
#> integer64
#> [1] <NA>
# very strange numbers
bit64::as.integer64(-9223372036854775295)
#> integer64
#> [1] -9223372036854774784
# very strange numbers
bit64::as.integer64(9223372036854775295)
#> integer64
#> [1] 9223372036854774784
# start of NA
bit64::as.integer64(-9223372036854775296)
#> integer64
#> [1] <NA>
# start of NA
bit64::as.integer64(9223372036854775296)
#> integer64
#> [1] <NA>
# above 9 999 999 999 999 998 starts rounding by 1:
bit64::as.integer64(-9999999999999999)
#> integer64
#> [1] -10000000000000000
bit64::as.integer64(9999999999999999)
#> integer64
#> [1] 10000000000000000
bit64::as.integer64(-9999999999999998)
#> integer64
#> [1] -9999999999999998
bit64::as.integer64(9999999999999998)
#> integer64
#> [1] 9999999999999998
bit64::as.integer64(9.999999999999999e+15)
#> integer64
#> [1] 10000000000000000
bit64::as.integer64(9.999999999999998e+15)
#> integer64
#> [1] 9999999999999998
```

<sup>Created on 2021-01-22 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

`

**Comment by greeNsort** [comment]
You are erroneously assuming that your input numbers are precise, but they are not, because R considers them to be double before converting to integer64. Look at this: 
`
> lim.integer64()
integer64
[1] -9223372036854775807 9223372036854775807 
> str(-9223372036854775808)
 num -9.22e+18
> -9223372036854775807 == -9223372036854775808
[1] TRUE
`using strings every thing is fine
`
> bit64::as.integer64("-9223372036854775807")
integer64
[1] -9223372036854775807
> bit64::as.integer64("-9223372036854775808")
integer64
[1] <NA>
`
